#ifndef STATUS_H
#define STATUS_h

#define COLOUR_1 DARKGRAY 
#define COLOUR_2 BLACK 

#define SUCCESS 0
#define NO_INIT_WINDOW_ERR -1
#define INVALID_COLOUR_ERR -2
#define INVALID_REFRESH_RATE_ERR -3
#define WINDOW_SIZING_ERR -4

#endif